# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - Подключить <a href="https://t.me/CP_VPNBot">ChillPad VPN</a>
  - about.md

footer: <a href="https://t.me/CP_VPNBot">Подключить ChillPad VPN</a>
privacy: <a href="/privacy">Политика конфиденциальности</a>
terms: <a href="/terms">Пользовательское соглашение</a>

style: light # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag

remote_theme: b2a3e8/jekyll-theme-console