# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'Подключить <a href="https://t.me/CP_VPNBot">ChillPad VPN</a> | Политика конфиденциальности | Пользовательское соглашение'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
